//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8670
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace DGP.Entities.Ventas {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsLineaVenta")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsLineaVenta : global::System.Data.DataSet {
        
        private DTLineaVentaDataTable tableDTLineaVenta;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsLineaVenta() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsLineaVenta(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["DTLineaVenta"] != null)) {
                    base.Tables.Add(new DTLineaVentaDataTable(ds.Tables["DTLineaVenta"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public DTLineaVentaDataTable DTLineaVenta {
            get {
                return this.tableDTLineaVenta;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dsLineaVenta cln = ((dsLineaVenta)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["DTLineaVenta"] != null)) {
                    base.Tables.Add(new DTLineaVentaDataTable(ds.Tables["DTLineaVenta"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableDTLineaVenta = ((DTLineaVentaDataTable)(base.Tables["DTLineaVenta"]));
            if ((initTable == true)) {
                if ((this.tableDTLineaVenta != null)) {
                    this.tableDTLineaVenta.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsLineaVenta";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsLineaVenta.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableDTLineaVenta = new DTLineaVentaDataTable();
            base.Tables.Add(this.tableDTLineaVenta);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeDTLineaVenta() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsLineaVenta ds = new dsLineaVenta();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void DTLineaVentaRowChangeEventHandler(object sender, DTLineaVentaRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class DTLineaVentaDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnIdLineaVenta;
            
            private global::System.Data.DataColumn columnCantidadJavas;
            
            private global::System.Data.DataColumn columnFlagJava;
            
            private global::System.Data.DataColumn columnTaraEditada;
            
            private global::System.Data.DataColumn columnPesoJava;
            
            private global::System.Data.DataColumn columnPesoBruto;
            
            private global::System.Data.DataColumn columnPesoTara;
            
            private global::System.Data.DataColumn columnPesoNeto;
            
            private global::System.Data.DataColumn columnEsPesoTaraEditado;
            
            private global::System.Data.DataColumn columnObservacion;
            
            private global::System.Data.DataColumn columnIdVenta;
            
            private global::System.Data.DataColumn columnIdAccion;
            
            private global::System.Data.DataColumn columnIdEstado;
            
            private global::System.Data.DataColumn columnEsDevolucion;
            
            private global::System.Data.DataColumn columnUnidades;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public DTLineaVentaDataTable() {
                this.TableName = "DTLineaVenta";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal DTLineaVentaDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected DTLineaVentaDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn IdLineaVentaColumn {
                get {
                    return this.columnIdLineaVenta;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CantidadJavasColumn {
                get {
                    return this.columnCantidadJavas;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FlagJavaColumn {
                get {
                    return this.columnFlagJava;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TaraEditadaColumn {
                get {
                    return this.columnTaraEditada;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PesoJavaColumn {
                get {
                    return this.columnPesoJava;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PesoBrutoColumn {
                get {
                    return this.columnPesoBruto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PesoTaraColumn {
                get {
                    return this.columnPesoTara;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PesoNetoColumn {
                get {
                    return this.columnPesoNeto;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn EsPesoTaraEditadoColumn {
                get {
                    return this.columnEsPesoTaraEditado;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ObservacionColumn {
                get {
                    return this.columnObservacion;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn IdVentaColumn {
                get {
                    return this.columnIdVenta;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn IdAccionColumn {
                get {
                    return this.columnIdAccion;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn IdEstadoColumn {
                get {
                    return this.columnIdEstado;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn EsDevolucionColumn {
                get {
                    return this.columnEsDevolucion;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn UnidadesColumn {
                get {
                    return this.columnUnidades;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public DTLineaVentaRow this[int index] {
                get {
                    return ((DTLineaVentaRow)(this.Rows[index]));
                }
            }
            
            public event DTLineaVentaRowChangeEventHandler DTLineaVentaRowChanging;
            
            public event DTLineaVentaRowChangeEventHandler DTLineaVentaRowChanged;
            
            public event DTLineaVentaRowChangeEventHandler DTLineaVentaRowDeleting;
            
            public event DTLineaVentaRowChangeEventHandler DTLineaVentaRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddDTLineaVentaRow(DTLineaVentaRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public DTLineaVentaRow AddDTLineaVentaRow(int IdLineaVenta, string CantidadJavas, string FlagJava, string TaraEditada, string PesoJava, string PesoBruto, string PesoTara, string PesoNeto, string EsPesoTaraEditado, string Observacion, int IdVenta, int IdAccion, string IdEstado, string EsDevolucion, int Unidades) {
                DTLineaVentaRow rowDTLineaVentaRow = ((DTLineaVentaRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        IdLineaVenta,
                        CantidadJavas,
                        FlagJava,
                        TaraEditada,
                        PesoJava,
                        PesoBruto,
                        PesoTara,
                        PesoNeto,
                        EsPesoTaraEditado,
                        Observacion,
                        IdVenta,
                        IdAccion,
                        IdEstado,
                        EsDevolucion,
                        Unidades};
                rowDTLineaVentaRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowDTLineaVentaRow);
                return rowDTLineaVentaRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                DTLineaVentaDataTable cln = ((DTLineaVentaDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new DTLineaVentaDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnIdLineaVenta = base.Columns["IdLineaVenta"];
                this.columnCantidadJavas = base.Columns["CantidadJavas"];
                this.columnFlagJava = base.Columns["FlagJava"];
                this.columnTaraEditada = base.Columns["TaraEditada"];
                this.columnPesoJava = base.Columns["PesoJava"];
                this.columnPesoBruto = base.Columns["PesoBruto"];
                this.columnPesoTara = base.Columns["PesoTara"];
                this.columnPesoNeto = base.Columns["PesoNeto"];
                this.columnEsPesoTaraEditado = base.Columns["EsPesoTaraEditado"];
                this.columnObservacion = base.Columns["Observacion"];
                this.columnIdVenta = base.Columns["IdVenta"];
                this.columnIdAccion = base.Columns["IdAccion"];
                this.columnIdEstado = base.Columns["IdEstado"];
                this.columnEsDevolucion = base.Columns["EsDevolucion"];
                this.columnUnidades = base.Columns["Unidades"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnIdLineaVenta = new global::System.Data.DataColumn("IdLineaVenta", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIdLineaVenta);
                this.columnCantidadJavas = new global::System.Data.DataColumn("CantidadJavas", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCantidadJavas);
                this.columnFlagJava = new global::System.Data.DataColumn("FlagJava", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFlagJava);
                this.columnTaraEditada = new global::System.Data.DataColumn("TaraEditada", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTaraEditada);
                this.columnPesoJava = new global::System.Data.DataColumn("PesoJava", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPesoJava);
                this.columnPesoBruto = new global::System.Data.DataColumn("PesoBruto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPesoBruto);
                this.columnPesoTara = new global::System.Data.DataColumn("PesoTara", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPesoTara);
                this.columnPesoNeto = new global::System.Data.DataColumn("PesoNeto", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPesoNeto);
                this.columnEsPesoTaraEditado = new global::System.Data.DataColumn("EsPesoTaraEditado", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEsPesoTaraEditado);
                this.columnObservacion = new global::System.Data.DataColumn("Observacion", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnObservacion);
                this.columnIdVenta = new global::System.Data.DataColumn("IdVenta", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIdVenta);
                this.columnIdAccion = new global::System.Data.DataColumn("IdAccion", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIdAccion);
                this.columnIdEstado = new global::System.Data.DataColumn("IdEstado", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnIdEstado);
                this.columnEsDevolucion = new global::System.Data.DataColumn("EsDevolucion", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEsDevolucion);
                this.columnUnidades = new global::System.Data.DataColumn("Unidades", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUnidades);
                this.columnIdLineaVenta.AllowDBNull = false;
                this.columnIdLineaVenta.DefaultValue = ((int)(0));
                this.columnCantidadJavas.MaxLength = 5;
                this.columnFlagJava.DefaultValue = ((string)("N"));
                this.columnFlagJava.MaxLength = 1;
                this.columnTaraEditada.MaxLength = 10;
                this.columnPesoJava.MaxLength = 10;
                this.columnPesoBruto.MaxLength = 10;
                this.columnPesoTara.MaxLength = 10;
                this.columnPesoNeto.MaxLength = 10;
                this.columnEsPesoTaraEditado.DefaultValue = ((string)("N"));
                this.columnEsPesoTaraEditado.MaxLength = 1;
                this.columnObservacion.MaxLength = 500;
                this.columnIdAccion.DefaultValue = ((int)(0));
                this.columnIdEstado.MaxLength = 5;
                this.columnEsDevolucion.MaxLength = 1;
                this.columnUnidades.DefaultValue = ((int)(0));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public DTLineaVentaRow NewDTLineaVentaRow() {
                return ((DTLineaVentaRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new DTLineaVentaRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(DTLineaVentaRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.DTLineaVentaRowChanged != null)) {
                    this.DTLineaVentaRowChanged(this, new DTLineaVentaRowChangeEvent(((DTLineaVentaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.DTLineaVentaRowChanging != null)) {
                    this.DTLineaVentaRowChanging(this, new DTLineaVentaRowChangeEvent(((DTLineaVentaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.DTLineaVentaRowDeleted != null)) {
                    this.DTLineaVentaRowDeleted(this, new DTLineaVentaRowChangeEvent(((DTLineaVentaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.DTLineaVentaRowDeleting != null)) {
                    this.DTLineaVentaRowDeleting(this, new DTLineaVentaRowChangeEvent(((DTLineaVentaRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveDTLineaVentaRow(DTLineaVentaRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsLineaVenta ds = new dsLineaVenta();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "DTLineaVentaDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class DTLineaVentaRow : global::System.Data.DataRow {
            
            private DTLineaVentaDataTable tableDTLineaVenta;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal DTLineaVentaRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableDTLineaVenta = ((DTLineaVentaDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int IdLineaVenta {
                get {
                    return ((int)(this[this.tableDTLineaVenta.IdLineaVentaColumn]));
                }
                set {
                    this[this.tableDTLineaVenta.IdLineaVentaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CantidadJavas {
                get {
                    try {
                        return ((string)(this[this.tableDTLineaVenta.CantidadJavasColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CantidadJavas\' in table \'DTLineaVenta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTLineaVenta.CantidadJavasColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FlagJava {
                get {
                    try {
                        return ((string)(this[this.tableDTLineaVenta.FlagJavaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FlagJava\' in table \'DTLineaVenta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTLineaVenta.FlagJavaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TaraEditada {
                get {
                    try {
                        return ((string)(this[this.tableDTLineaVenta.TaraEditadaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TaraEditada\' in table \'DTLineaVenta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTLineaVenta.TaraEditadaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PesoJava {
                get {
                    try {
                        return ((string)(this[this.tableDTLineaVenta.PesoJavaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PesoJava\' in table \'DTLineaVenta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTLineaVenta.PesoJavaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PesoBruto {
                get {
                    try {
                        return ((string)(this[this.tableDTLineaVenta.PesoBrutoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PesoBruto\' in table \'DTLineaVenta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTLineaVenta.PesoBrutoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PesoTara {
                get {
                    try {
                        return ((string)(this[this.tableDTLineaVenta.PesoTaraColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PesoTara\' in table \'DTLineaVenta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTLineaVenta.PesoTaraColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PesoNeto {
                get {
                    try {
                        return ((string)(this[this.tableDTLineaVenta.PesoNetoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PesoNeto\' in table \'DTLineaVenta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTLineaVenta.PesoNetoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string EsPesoTaraEditado {
                get {
                    try {
                        return ((string)(this[this.tableDTLineaVenta.EsPesoTaraEditadoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'EsPesoTaraEditado\' in table \'DTLineaVenta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTLineaVenta.EsPesoTaraEditadoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Observacion {
                get {
                    if (this.IsObservacionNull()) {
                        return string.Empty;
                    }
                    else {
                        return ((string)(this[this.tableDTLineaVenta.ObservacionColumn]));
                    }
                }
                set {
                    this[this.tableDTLineaVenta.ObservacionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int IdVenta {
                get {
                    try {
                        return ((int)(this[this.tableDTLineaVenta.IdVentaColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'IdVenta\' in table \'DTLineaVenta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTLineaVenta.IdVentaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int IdAccion {
                get {
                    try {
                        return ((int)(this[this.tableDTLineaVenta.IdAccionColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'IdAccion\' in table \'DTLineaVenta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTLineaVenta.IdAccionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string IdEstado {
                get {
                    try {
                        return ((string)(this[this.tableDTLineaVenta.IdEstadoColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'IdEstado\' in table \'DTLineaVenta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTLineaVenta.IdEstadoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string EsDevolucion {
                get {
                    try {
                        return ((string)(this[this.tableDTLineaVenta.EsDevolucionColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'EsDevolucion\' in table \'DTLineaVenta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTLineaVenta.EsDevolucionColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Unidades {
                get {
                    try {
                        return ((int)(this[this.tableDTLineaVenta.UnidadesColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'Unidades\' in table \'DTLineaVenta\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableDTLineaVenta.UnidadesColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCantidadJavasNull() {
                return this.IsNull(this.tableDTLineaVenta.CantidadJavasColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCantidadJavasNull() {
                this[this.tableDTLineaVenta.CantidadJavasColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFlagJavaNull() {
                return this.IsNull(this.tableDTLineaVenta.FlagJavaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFlagJavaNull() {
                this[this.tableDTLineaVenta.FlagJavaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTaraEditadaNull() {
                return this.IsNull(this.tableDTLineaVenta.TaraEditadaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTaraEditadaNull() {
                this[this.tableDTLineaVenta.TaraEditadaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPesoJavaNull() {
                return this.IsNull(this.tableDTLineaVenta.PesoJavaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPesoJavaNull() {
                this[this.tableDTLineaVenta.PesoJavaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPesoBrutoNull() {
                return this.IsNull(this.tableDTLineaVenta.PesoBrutoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPesoBrutoNull() {
                this[this.tableDTLineaVenta.PesoBrutoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPesoTaraNull() {
                return this.IsNull(this.tableDTLineaVenta.PesoTaraColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPesoTaraNull() {
                this[this.tableDTLineaVenta.PesoTaraColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPesoNetoNull() {
                return this.IsNull(this.tableDTLineaVenta.PesoNetoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPesoNetoNull() {
                this[this.tableDTLineaVenta.PesoNetoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsEsPesoTaraEditadoNull() {
                return this.IsNull(this.tableDTLineaVenta.EsPesoTaraEditadoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetEsPesoTaraEditadoNull() {
                this[this.tableDTLineaVenta.EsPesoTaraEditadoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsObservacionNull() {
                return this.IsNull(this.tableDTLineaVenta.ObservacionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetObservacionNull() {
                this[this.tableDTLineaVenta.ObservacionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIdVentaNull() {
                return this.IsNull(this.tableDTLineaVenta.IdVentaColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIdVentaNull() {
                this[this.tableDTLineaVenta.IdVentaColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIdAccionNull() {
                return this.IsNull(this.tableDTLineaVenta.IdAccionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIdAccionNull() {
                this[this.tableDTLineaVenta.IdAccionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsIdEstadoNull() {
                return this.IsNull(this.tableDTLineaVenta.IdEstadoColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetIdEstadoNull() {
                this[this.tableDTLineaVenta.IdEstadoColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsEsDevolucionNull() {
                return this.IsNull(this.tableDTLineaVenta.EsDevolucionColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetEsDevolucionNull() {
                this[this.tableDTLineaVenta.EsDevolucionColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsUnidadesNull() {
                return this.IsNull(this.tableDTLineaVenta.UnidadesColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetUnidadesNull() {
                this[this.tableDTLineaVenta.UnidadesColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class DTLineaVentaRowChangeEvent : global::System.EventArgs {
            
            private DTLineaVentaRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public DTLineaVentaRowChangeEvent(DTLineaVentaRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public DTLineaVentaRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591