USE [DVGP_CITAVAL]
GO

/****** Object:  Table [dbo].[Tb_TipoPago]    Script Date: 19/12/2017 10:25:41 p.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Tb_TipoPago](
	[IdTipoPago] [varchar](10) NOT NULL,
	[TipoPago] [varchar](50) NULL,
 CONSTRAINT [PK_tb_TipoPago] PRIMARY KEY CLUSTERED 
(
	[IdTipoPago] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

