USE [DVGP_CITAVAL]
GO

/****** Object:  Index [IDX_TB_VENTA_CLIENTE_CAJA]    Script Date: 01/10/2018 10:21:34 a.m. ******/
DROP INDEX [IDX_TB_VENTA_CLIENTE_CAJA] ON [dbo].[Tb_Venta]
GO

/****** Object:  Index [IDX_TB_VENTA_CLIENTE_CAJA]    Script Date: 01/10/2018 10:21:34 a.m. ******/
CREATE NONCLUSTERED INDEX [IDX_TB_VENTA_CLIENTE_CAJA] ON [dbo].[Tb_Venta]
(
	[Id_Cliente] ASC,
	[Id_Caja] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


