USE [DVGP_CITAVAL]
GO

/****** Object:  Index [IDX_TB_CAJA_FECHA]    Script Date: 01/10/2018 10:18:03 a.m. ******/
DROP INDEX [IDX_TB_CAJA_FECHA] ON [dbo].[Tb_Caja]
GO

/****** Object:  Index [IDX_TB_CAJA_FECHA]    Script Date: 01/10/2018 10:18:03 a.m. ******/
CREATE NONCLUSTERED INDEX [IDX_TB_CAJA_FECHA] ON [dbo].[Tb_Caja]
(
	[Fecha] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


